export const InvitedMembers = [
    { value: "All EU countries", label: "All EU countries" },
    { value: "Germany", label: "Germany" },
    { value: "Austria", label: "Austria" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Albania", label: "Albania" },
    { value: "Belgium", label: "Belgium" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Belarus", label: "Belarus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Croatia", label: "Croatia" },
    { value: "Denmark", label: "Denmark" },
    { value: "Estonia", label: "Estonia" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "Greece", label: "Greece" },
    { value: "Hungary", label: "Hungary" },
    { value: "Ireland", label: "Ireland" },
    { value: "Iceland", label: "Iceland" },
    { value: "Italy", label: "Italy" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Latvia", label: "Latvia" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "Norway", label: "Norway" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Romania", label: "Romania" },
    { value: "Spain", label: "Spain" },
    { value: "Sweden", label: "Sweden" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "United Kingdom", label: "United Kingdom" },
  ];